sudo: required
dist: xenial
matrix:
  include:
  # Linux
  - language: python
    python: 2.7
    os: linux
    env: TOX_ENV=linux
  - language: python
    python: 3.6
    os: linux
    env: TOX_ENV=linux
  - language: python
    python: 3.7
    os: linux
    env: TOX_ENV=linux
  - language: python
    python: 3.8
    os: linux
    env: TOX_ENV=linux
  # OSX
  - language: python
    python: 2.7
    os: osx
    env: TOX_ENV=osx
  - language: python
    python: 3.6
    os: osx
    env: TOX_ENV=osx
  - language: python
    python: 3.7
    os: osx
    env: TOX_ENV=osx
  - language: python
    python: 3.8
    os: osx
    env: TOX_ENV=osx

  # Windows
  # No python support by default, so install it separately
  - language: shell
    os: windows
    env:
      - TOX_ENV=windows
      - PY_VERSION=2
      - PY_SUBVERSION=2.7.15
      - PATH=/c/Python27:/c/Python27/Scripts:$PATH
  - language: shell
    os: windows
    env:
      - TOX_ENV=windows
      - PY_VERSION=3
      - PY_SUBVERSION=3.6
      - PATH=/c/Python36:/c/Python36/Scripts:$PATH
  - language: shell
    os: windows
    env:
      - TOX_ENV=windows
      - PY_VERSION=3
      - PY_SUBVERSION=3.7
      - PATH=/c/Python37:/c/Python37/Scripts:$PATH
  - language: shell
    os: windows
    env:
      - TOX_ENV=windows
      - PY_VERSION=3
      - PY_SUBVERSION=3.8
      - PATH=/c/Python38:/c/Python38/Scripts:$PATH

  # Lint
  # Only run linting on the latest python version
  - language: python
    python: 3.8
    env: TOX_ENV=lint
install:
- if [ $TRAVIS_OS_NAME == "windows" ]; then choco install python$PY_VERSION --version=$PY_SUBVERSION; fi
- python --version
- python -m pip install --upgrade pip
- pip install tox coveralls
script:
- tox -e $TOX_ENV
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
after_success:
- coveralls
