os:
  - linux
  - windows

language: python
sudo: required
dist: xenial
matrix:
  include:
  - python: 2.7
    env: TOX_ENV=test
  - python: 3.6
    env: TOX_ENV=test
  - python: 3.7
    env: TOX_ENV=test
  - python: 3.8
    env: TOX_ENV=test
  - python: 3.8
    env: TOX_ENV=flake8
install:
- pip install tox coveralls
script:
- if [ $TRAVIS_OS_NAME == "windows" ]; then tox -e $TOX_ENV -- -k win; fi
- if [ $TRAVIS_OS_NAME == "linux" ]; then tox -e $TOX_ENV -- -k linux; fi
- if [ $TOX_ENV == "flake8" ]; then tox -e $TOX_ENV; fi
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
after_success:
- coveralls
