sudo: required
dist: xenial
matrix:
  include:
  # Linux
  - language: python
    python: 2.7
    os: linux
  - language: python
    python: 3.6
    os: linux
  - language: python
    python: 3.7
    os: linux
  - language: python
    python: 3.8
    os: linux

  # OSX
  - language: shell
    os: osx
    osx_image: xcode9.3
    env:
      - PY_VERSION=2
  - language: shell
    os: osx
    osx_image: xcode9.4
    env:
      - PY_VERSION=3
  - language: shell
    os: osx
    osx_image: xcode10.2
    env:
      - PY_VERSION=3
  - language: shell
    os: osx
    osx_image: xcode11.3
    env:
      - PY_VERSION=3

  # Windows
  # No python support by default, so install it separately
  - language: shell
    os: windows
    env:
      - PY_VERSION=2
      - PY_SUBVERSION=2.7.15
      - PATH=/c/Python27:/c/Python27/Scripts:$PATH
  - language: shell
    os: windows
    env:
      - PY_VERSION=3
      - PY_SUBVERSION=3.6.5
      - PATH=/c/Python36:/c/Python36/Scripts:$PATH
  - language: shell
    os: windows
    env:
      - PY_VERSION=3
      - PY_SUBVERSION=3.7
      - PATH=/c/Python37:/c/Python37/Scripts:$PATH
  - language: shell
    os: windows
    env:
      - PY_VERSION=3
      - PY_SUBVERSION=3.8
      - PATH=/c/Python38:/c/Python38/Scripts:$PATH

  # Lint
  # Only run linting on the latest python version
  - language: python
    python: 3.8
    env: TOX_ENV=lint

install:
# Windows
- if [ $TRAVIS_OS_NAME == "windows" ]; then choco install python$PY_VERSION --version=$PY_SUBVERSION; fi
- if [ $TRAVIS_OS_NAME == "windows" ]; then python --version; fi
- if [ $TRAVIS_OS_NAME == "windows" ]; then python -m pip install --upgrade pip; fi
- if [ $TRAVIS_OS_NAME == "windows" ]; then pip install tox coveralls; fi

# OSX
- if [[ $TRAVIS_OS_NAME == "osx" && $PY_VERSION == 2 ]]; then python --version; fi
- if [[ $TRAVIS_OS_NAME == "osx" && $PY_VERSION == 2 ]]; then sudo pip install --ignore-installed tox coveralls; fi

- if [[ $TRAVIS_OS_NAME == "osx" && $PY_VERSION == 3 ]]; then python3 --version; fi
- if [[ $TRAVIS_OS_NAME == "osx" && $PY_VERSION == 3 ]]; then pip3 install -U pip; fi
- if [[ $TRAVIS_OS_NAME == "osx" && $PY_VERSION == 3 ]]; then pip3 install tox coveralls; fi

# Linux
- if [ $TRAVIS_OS_NAME == "linux" ]; then pip install tox coveralls; fi

script:
- tox -e $TRAVIS_OS_NAME
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
after_success:
- coveralls
